FROM python:3.9

WORKDIR /workspace
COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "akaike:app", "--host", "0.0.0.0", "--port", "7860"]

